### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by hidayatambo** [stephenjhs/perpusqu#2]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/72801930/209715954-3fb162b5-50d9-4c9d-b4c7-38483a0a39cb.png">
eroor 500 peminjaman oleh anggota
<img width="1440" alt="Jepretan Layar 2022-12-28 pukul 02 53 03" src="https://user-images.githubusercontent.com/72801930/209716064-1254972b-25a3-473b-9144-f337f75f51a4.png">

**Comment by stephenjhs** [comment]
Hmm diaku gk ad masalah knp ya

**Comment by hidayatambo** [comment]
jadi pas siswa mau minjam error mas

**Comment by stephenjhs** [comment]
ooh maslaahnya ada di tabel peminjaman.pengguna_id 
coba kamu edit attribut default ny menjadi null.
semoga membantu hehe

**Comment by hidayatambo** [comment]
sip worked mas! thnk u
